[project]
name = 'Decentralized-Temporal-Paradox-Resolution-Framework'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.causal-loop-detection]
path = 'contracts/causal-loop-detection.clar'
clarity_version = 2
epoch = 2.5

[contracts.timeline-integrity]
path = 'contracts/timeline-integrity.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
